### ISSUE TITLE
`hotel ls` returns empty after upgrade to v0.5.1

### ISSUE THREAD

**Issue by rajasharan** [typicode/hotel#108]
I was on a previous version of hotel (can't remember the version).
Just today I upgraded hotel with `npm i -g hotel` to 0.5.1

When I run `hotel ls` it shows empty (only the app name shows up) - even the localhost:2000 gui is missing all entries.

I manually checked `~/.hotel/servers/` - all files are still intact. So I don't understand why the newer version is not picking up the files from the servers folder

**Comment by typicode** [comment]
Hi @rajasharan,

Thanks for the report. That's weird, I can't seem to reproduce.
Do you have any error in `~/.hotel/daemon.log` or in the browser console?
What's your OS?

**Comment by rajasharan** [comment]
@typicode - yes I do have some errors in `daemon.log`
(I'm on OS X - 10.11.5, node v6.2.2, npm 3.9.5)
(I do remember I upgraded my node also from 4.x.x - not sure if playa part in this issue)


```sh
28 Apr 02:00:17 - Watching /Users/raja/.hotel/servers
create /Users/raja/.hotel/daemon.pid 9445
28 Apr 02:00:17 - Server listening on port 127.0.0.1:2000
28 Apr 02:02:07 - Redirect - can't find server for favicon.ico
28 Apr 02:05:56 - Created /Users/raja/.hotel/servers/cocoa-app.json
28 Apr 02:05:56 - Add server id: cocoa-app cmd: gcc -framework Cocoa -x objective-c -o MinimalApp minimal.objc ; ./MinimalApp port: 61800
28 Apr 02:06:19 - cocoa-app has started
28 Apr 02:06:23 - cocoa-app has stopped
28 Apr 02:06:25 - cocoa-app has started
28 Apr 02:06:28 - cocoa-app has stopped
28 Apr 02:07:41 - Redirect - can't find server for favicon.ico
28 Apr 02:07:42 - Redirect - can't find server for favicon.ico
28 Apr 02:07:44 - Redirect - can't find server for favicon.ico
28 Apr 02:07:46 - Redirect - can't find server for favicon.ico
28 Apr 02:07:48 - cocoa-app has started
28 Apr 02:07:50 - cocoa-app has stopped
28 Apr 02:07:52 - cocoa-app has started
28 Apr 02:07:54 - cocoa-app has stopped
28 Apr 02:11:28 - Created /Users/raja/.hotel/servers/us-map.json
28 Apr 02:11:28 - Add server id: us-map cmd: lite-server port: 61835
28 Apr 02:11:47 - us-map has started
28 Apr 02:14:44 - us-map has stopped
28 Apr 02:14:52 - us-map has started
28 Apr 02:15:03 - us-map has stopped
28 Apr 02:40:21 - Created /Users/raja/.hotel/servers/capoeira-hq.json
28 Apr 02:40:21 - Add server id: capoeira-hq cmd: gulp port: 62086
28 Apr 02:40:37 - Redirect - can't find server for favicon.ico
28 Apr 02:40:41 - capoeira-hq has started
28 Apr 02:41:21 - capoeira-hq has stopped
30 Apr 12:14:12 - Created /Users/raja/.hotel/servers/password-manager-js.json
30 Apr 12:14:12 - Add server id: password-manager-js cmd: lite-server port: 52521
30 Apr 12:31:05 - Redirect - can't find server for favicon.ico
30 Apr 12:31:14 - password-manager-js has started
30 Apr 12:55:37 - password-manager-js has stopped
30 Apr 13:03:38 - Redirect - can't find server for favicon.ico
(node) warning: possible EventEmitter memory leak detected. 11 stdout listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:239:17)
    at /usr/local/lib/node_modules/hotel/lib/daemon/events/index.js:32:9
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:131:13)
    at sse (/usr/local/lib/node_modules/hotel/node_modules/connect-sse/index.js:18:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/hotel/node_modules/express/lib/router/index.js:277:22
(node) warning: possible EventEmitter memory leak detected. 11 stderr listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:239:17)
    at /usr/local/lib/node_modules/hotel/lib/daemon/events/index.js:33:9
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:131:13)
    at sse (/usr/local/lib/node_modules/hotel/node_modules/connect-sse/index.js:18:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/hotel/node_modules/express/lib/router/index.js:277:22
30 Apr 19:25:29 - cocoa-app has started
30 Apr 19:25:34 - Redirect - can't find server for favicon.ico
30 Apr 19:25:46 - Redirect - can't find server for favicon.ico
30 Apr 19:25:54 - Redirect - can't find server for favicon.ico
30 Apr 19:25:58 - Redirect - can't find server for favicon.ico
30 Apr 19:26:00 - cocoa-app has stopped
(node) warning: possible EventEmitter memory leak detected. 11 stdout listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:239:17)
    at /usr/local/lib/node_modules/hotel/lib/daemon/events/index.js:32:9
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:131:13)
    at sse (/usr/local/lib/node_modules/hotel/node_modules/connect-sse/index.js:18:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/hotel/node_modules/express/lib/router/index.js:277:22
(node) warning: possible EventEmitter memory leak detected. 11 stderr listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:239:17)
    at /usr/local/lib/node_modules/hotel/lib/daemon/events/index.js:33:9
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:131:13)
    at sse (/usr/local/lib/node_modules/hotel/node_modules/connect-sse/index.js:18:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/hotel/node_modules/express/lib/router/index.js:277:22
30 Apr 19:26:05 - us-map has started
30 Apr 19:26:17 - Redirect - can't find server for favicon.ico
(node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at /usr/local/lib/node_modules/hotel/lib/daemon/events/index.js:16:13
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:131:13)
    at sse (/usr/local/lib/node_modules/hotel/node_modules/connect-sse/index.js:18:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/hotel/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/hotel/node_modules/express/lib/router/index.js:277:22
30 Apr 19:26:21 - Redirect - can't find server for favicon.ico
30 Apr 19:26:29 - us-map has stopped
30 Apr 19:26:31 - us-map has started
30 Apr 19:26:53 - us-map has stopped
30 Apr 19:27:03 - cocoa-app has started
30 Apr 19:27:10 - cocoa-app has stopped
8 May 11:24:43 - Watching /Users/raja/.hotel/servers
create /Users/raja/.hotel/daemon.pid 511
8 May 11:24:44 - Server listening on port 127.0.0.1:2000
8 May 11:24:44 - Add server id: capoeira-hq cmd: gulp port: 49375
8 May 11:24:44 - Add server id: cocoa-app cmd: gcc -framework Cocoa -x objective-c -o MinimalApp minimal.objc ; ./MinimalApp port: 49376
8 May 11:24:44 - Add server id: password-manager-js cmd: lite-server port: 49377
8 May 11:24:44 - Add server id: us-map cmd: lite-server port: 49378
8 May 11:24:44 - Created /Users/raja/.hotel/servers/capoeira-hq.json
8 May 11:24:44 - Created /Users/raja/.hotel/servers/cocoa-app.json
8 May 11:24:44 - Created /Users/raja/.hotel/servers/password-manager-js.json
8 May 11:24:44 - Created /Users/raja/.hotel/servers/us-map.json
8 May 11:24:44 - Add server id: capoeira-hq cmd: gulp port: 49387
8 May 11:24:44 - Add server id: cocoa-app cmd: gcc -framework Cocoa -x objective-c -o MinimalApp minimal.objc ; ./MinimalApp port: 49388
8 May 11:24:44 - Add server id: password-manager-js cmd: lite-server port: 49389
8 May 11:24:44 - Add server id: us-map cmd: lite-server port: 49390
9 May 20:47:49 - Redirect - can't find server for favicon.ico
9 May 20:47:53 - capoeira-hq has started
9 May 20:59:37 - capoeira-hq has stopped
9 May 20:59:42 - capoeira-hq has started
9 May 21:17:53 - capoeira-hq has stopped
14 May 21:57:33 - Redirect - can't find server for favicon.ico
14 May 21:57:36 - capoeira-hq has started
14 May 22:16:51 - capoeira-hq has stopped
Exiting
Stop daemon
Remove pid file
4 Jun 10:42:43 - Watching /Users/raja/.hotel/servers
create /Users/raja/.hotel/daemon.pid 560
4 Jun 10:42:43 - Server listening on port 127.0.0.1:2000
4 Jun 10:42:43 - Add server id: capoeira-hq cmd: gulp port: 49237
4 Jun 10:42:43 - Add server id: cocoa-app cmd: gcc -framework Cocoa -x objective-c -o MinimalApp minimal.objc ; ./MinimalApp port: 49238
4 Jun 10:42:43 - Add server id: password-manager-js cmd: lite-server port: 49239
4 Jun 10:42:43 - Add server id: us-map cmd: lite-server port: 49240
4 Jun 10:42:43 - Created /Users/raja/.hotel/servers/capoeira-hq.json
4 Jun 10:42:43 - Created /Users/raja/.hotel/servers/cocoa-app.json
4 Jun 10:42:43 - Created /Users/raja/.hotel/servers/password-manager-js.json
4 Jun 10:42:43 - Created /Users/raja/.hotel/servers/us-map.json
4 Jun 10:42:43 - Add server id: capoeira-hq cmd: gulp port: 49242
4 Jun 10:42:43 - Add server id: cocoa-app cmd: gcc -framework Cocoa -x objective-c -o MinimalApp minimal.objc ; ./MinimalApp port: 49243
4 Jun 10:42:43 - Add server id: password-manager-js cmd: lite-server port: 49244
4 Jun 10:42:43 - Add server id: us-map cmd: lite-server port: 49245
4 Jun 11:07:35 - Created /Users/raja/.hotel/servers/transducers.json
4 Jun 11:07:35 - Add server id: transducers cmd: lite-server port: 49997
4 Jun 11:07:52 - Redirect - can't find server for favicon.ico
4 Jun 11:07:55 - transducers has started
4 Jun 11:08:00 - Redirect - can't find server for favicon.ico
4 Jun 11:08:19 - Redirect - can't find server for favicon.ico
4 Jun 11:08:25 - transducers has stopped
4 Jun 11:08:35 - transducers has started
4 Jun 13:13:04 - Created /Users/raja/.hotel/servers/elm-tutorial.json
4 Jun 13:13:04 - Add server id: elm-tutorial cmd: elm reactor port: 50870
4 Jun 13:13:14 - Redirect - can't find server for favicon.ico
4 Jun 13:13:16 - transducers has stopped
4 Jun 13:13:23 - elm-tutorial has started
5 Jun 12:36:42 - Redirect - can't find server for favicon.ico
5 Jun 12:36:44 - elm-tutorial has stopped
5 Jun 12:41:37 - Redirect - can't find server for favicon.ico
5 Jun 12:41:45 - elm-tutorial has started
5 Jun 12:41:46 - elm-tutorial has stopped
5 Jun 12:41:52 - elm-tutorial has started
5 Jun 12:41:52 - elm-tutorial has stopped
5 Jun 12:42:01 - elm-tutorial has started
5 Jun 12:57:42 - Redirect - can't find server for favicon.ico
5 Jun 13:19:42 - Created /Users/raja/.hotel/servers/elm-raycaster.json
5 Jun 13:19:42 - Add server id: elm-raycaster cmd: elm reactor port: 54807
5 Jun 13:27:51 - Redirect - can't find server for favicon.ico
11 Jun 02:32:32 - Redirect - can't find server for favicon.ico
11 Jun 02:32:33 - elm-tutorial has stopped
11 Jun 07:14:52 - Watching /Users/raja/.hotel/servers
create /Users/raja/.hotel/daemon.pid 507
11 Jun 07:14:53 - Server listening on port 127.0.0.1:2000
11 Jun 07:14:53 - Add server id: capoeira-hq cmd: gulp port: 49165
11 Jun 07:14:53 - Add server id: cocoa-app cmd: gcc -framework Cocoa -x objective-c -o MinimalApp minimal.objc ; ./MinimalApp port: 49166
11 Jun 07:14:53 - Add server id: elm-raycaster cmd: elm reactor port: 49167
11 Jun 07:14:53 - Add server id: elm-tutorial cmd: elm reactor port: 49168
11 Jun 07:14:53 - Add server id: password-manager-js cmd: lite-server port: 49169
11 Jun 07:14:53 - Add server id: transducers cmd: lite-server port: 49170
11 Jun 07:14:53 - Add server id: us-map cmd: lite-server port: 49171
11 Jun 07:14:53 - Created /Users/raja/.hotel/servers/capoeira-hq.json
11 Jun 07:14:53 - Created /Users/raja/.hotel/servers/elm-raycaster.json
11 Jun 07:14:53 - Created /Users/raja/.hotel/servers/cocoa-app.json
11 Jun 07:14:53 - Created /Users/raja/.hotel/servers/elm-tutorial.json
11 Jun 07:14:53 - Created /Users/raja/.hotel/servers/password-manager-js.json
11 Jun 07:14:53 - Created /Users/raja/.hotel/servers/transducers.json
11 Jun 07:14:53 - Created /Users/raja/.hotel/servers/us-map.json
11 Jun 07:14:53 - Add server id: capoeira-hq cmd: gulp port: 49175
11 Jun 07:14:53 - Add server id: elm-raycaster cmd: elm reactor port: 49176
11 Jun 07:14:53 - Add server id: cocoa-app cmd: gcc -framework Cocoa -x objective-c -o MinimalApp minimal.objc ; ./MinimalApp port: 49177
11 Jun 07:14:53 - Add server id: elm-tutorial cmd: elm reactor port: 49178
11 Jun 07:14:53 - Add server id: password-manager-js cmd: lite-server port: 49179
11 Jun 07:14:53 - Add server id: transducers cmd: lite-server port: 49180
11 Jun 07:14:53 - Add server id: us-map cmd: lite-server port: 49181
25 Jun 14:39:17 - Redirect - can't find server for favicon.ico
25 Jun 14:39:22 - password-manager-js has started
26 Jun 00:16:09 - Removed /Users/raja/.hotel/servers/password-manager-js.json
26 Jun 00:16:09 - password-manager-js has stopped
26 Jun 00:16:49 - Created /Users/raja/.hotel/servers/xtor-password-manager.json
26 Jun 00:16:49 - Add server id: xtor-password-manager cmd: lite-server port: 62230
26 Jun 00:17:17 - Redirect - can't find server for favicon.ico
26 Jun 00:17:20 - xtor-password-manager has started
26 Jun 00:17:58 - xtor-password-manager has stopped
26 Jun 00:18:03 - xtor-password-manager has started
26 Jun 12:25:44 - Redirect - can't find server for favicon.ico
26 Jun 12:25:51 - xtor-password-manager has stopped
26 Jun 12:25:51 - Redirect - can't find server for favicon.ico
26 Jun 12:25:54 - Redirect - can't find server for favicon.ico
26 Jun 12:25:57 - xtor-password-manager has started
26 Jun 12:46:18 - xtor-password-manager has stopped
26 Jun 12:48:36 - Redirect - can't find server for favicon.ico
26 Jun 15:34:23 - Created /Users/raja/.hotel/servers/elm-freehand-drawing.json
26 Jun 15:34:23 - Add server id: elm-freehand-drawing cmd: lite-server port: 63497
26 Jun 15:34:32 - Redirect - can't find server for favicon.ico
26 Jun 15:34:35 - elm-freehand-drawing has started
26 Jun 15:34:40 - Redirect - can't find server for favicon.ico
26 Jun 15:37:45 - Redirect - can't find server for favicon.ico
26 Jun 15:37:48 - Redirect - can't find server for favicon.ico
26 Jun 15:37:53 - Redirect - can't find server for favicon.ico
29 Jun 18:17:40 - elm-freehand-drawing has stopped
2 Jul 16:58:26 - Created /Users/raja/.hotel/servers/elm-graphics.json
2 Jul 16:58:26 - Add server id: elm-graphics cmd: lite-server port: 57843
2 Jul 16:58:45 - Redirect - can't find server for bundle.js
2 Jul 16:58:45 - Redirect - can't find server for favicon.ico
2 Jul 16:58:49 - Redirect - can't find server for bundle.js
2 Jul 16:58:49 - Redirect - can't find server for favicon.ico
2 Jul 17:14:43 - Redirect - can't find server for bundle.js
2 Jul 17:14:43 - Redirect - can't find server for favicon.ico
2 Jul 17:14:46 - Redirect - can't find server for {{href(id)}}
2 Jul 17:14:46 - Redirect - can't find server for bundle.js
2 Jul 17:14:46 - Redirect - can't find server for favicon.ico
2 Jul 17:14:47 - Redirect - can't find server for {{href(id)}}
2 Jul 17:14:48 - Redirect - can't find server for bundle.js
2 Jul 17:14:48 - Redirect - can't find server for favicon.ico
2 Jul 17:15:01 - Redirect - can't find server for bundle.js
2 Jul 17:15:01 - Redirect - can't find server for favicon.ico
2 Jul 17:15:35 - Redirect - can't find server for favicon.ico
2 Jul 17:15:36 - Redirect - can't find server for favicon.ico
3 Jul 07:08:33 - Redirect - can't find server for bundle.js
3 Jul 07:08:34 - Redirect - can't find server for favicon.ico
3 Jul 07:08:36 - Redirect - can't find server for {{href(id)}}
3 Jul 07:08:36 - Redirect - can't find server for bundle.js
3 Jul 07:08:36 - Redirect - can't find server for favicon.ico
3 Jul 07:08:38 - Redirect - can't find server for {{href(id)}}
3 Jul 07:08:38 - Redirect - can't find server for bundle.js
3 Jul 07:08:38 - Redirect - can't find server for favicon.ico
3 Jul 07:08:44 - Redirect - can't find server for favicon.ico
3 Jul 07:08:45 - Redirect - can't find server for favicon.ico
```

**Comment by rajasharan** [comment]
one error in browser console - but that must be because of missing data:

![image](https://cloud.githubusercontent.com/assets/299522/16568131/8643ea3c-41f4-11e6-9856-9458b7fab997.png)

**Comment by typicode** [comment]
Awesome, thanks for the update.
