### ISSUE TITLE
hotel crashes with "Error: Can't set headers after they are sent."

### ISSUE THREAD

**Issue by layerssss** [typicode/hotel#163]
Hi, there's a crash happens every time when I visit one page.

I'm developing a proxy program, and the crash happens only when I try to access the page on this url:

http://www.stuff.co.nz/technology

```
14 Jan 10:20:12 - Proxy http://pathifier.dev to http://localhost:42644
14 Jan 10:20:12 - Proxy error
Exiting
Stop daemon
Remove pid file
_http_outgoing.js:358
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:358:11)
    at ServerResponse.header (/home/michael.yin/.nvm/versions/node/v7.0.0/lib/node_modules/hotel/node_modules/express/lib/response.js:719:10)
    at ServerResponse.send (/home/michael.yin/.nvm/versions/node/v7.0.0/lib/node_modules/hotel/node_modules/express/lib/response.js:164:12)
    at ProxyServer.handleProxyError (/home/michael.yin/.nvm/versions/node/v7.0.0/lib/node_modules/hotel/lib/daemon/group.js:260:23)
    at ProxyServer.emit (/home/michael.yin/.nvm/versions/node/v7.0.0/lib/node_modules/hotel/node_modules/eventemitter3/index.js:144:27)
    at ClientRequest.proxyError (/home/michael.yin/.nvm/versions/node/v7.0.0/lib/node_modules/hotel/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:148:16)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnData (_http_client.js:367:9)
    at emitOne (events.js:96:13)
```

**Comment by typicode** [comment]
Hi @layerssss,

Thanks for the report.
Didn't check the code, but `hotel` daemon shouldn't crash so I'd say it's a bug.
