### ISSUE TITLE
Error: self signed certificate

### ISSUE THREAD

**Issue by eueung** [typicode/hotel#166]
Hi,

tried to execute hubot within hotel and got this message:

```
[Sat Jan 21 2017 10:03:13 GMT+0700 (WIB)] ERROR Error: self signed certificate
  at Error (native)
  at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
  at emitNone (events.js:86:13)
  at TLSSocket.emit (events.js:185:7)
  at TLSSocket._finishInit (_tls_wrap.js:603:8)
  at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
```

Previously was o.k. (prior to 0.5.13). 

Execution without hotel works as expected.

rgds.
EM

**Comment by djanowski** [comment]
Same here.

**Comment by djanowski** [comment]
Dup of #157.

**Comment by typicode** [comment]
Hi,

Could you try setting `http_proxy: false` in `~/.hotel/conf.json`?
