### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by productiveme** [typicode/hotel#179]
I'm trying to get hotel working on Elementary OS (based on Ubuntu 14.04). When installing without sudo, I get EACCES: permissions denied errors, and when installing with sudo, hotel simply won't start. The following appears in the deamon.log file:

2 Mar 12:09:34 - Watching /home/jaco/.hotel/servers
create /home/jaco/.hotel/daemon.pid 4635
2 Mar 12:09:34 - Server listening on port 127.0.0.1:2000
Exiting
Stop daemon
Remove pid file
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/jaco/.hotel/servers ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at createFsWatchInstance (/usr/lib/node_modules/hotel/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/lib/node_modules/hotel/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/lib/node_modules/hotel/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/usr/lib/node_modules/hotel/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/usr/lib/node_modules/hotel/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/usr/lib/node_modules/hotel/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)

Any pointers would be appreciated

**Comment by typicode** [comment]
Hi @productiveme,

Yes, the fix in https://github.com/typicode/hotel/issues/147 should probably help. Basically, `~/.hotel` should belong to user and not root.

**Comment by typicode** [comment]
I've created an issue for this particular case https://github.com/typicode/hotel/issues/178 and updated FAQ with the fix.
