### ISSUE TITLE
babel dependency

### ISSUE THREAD

**Issue by veggiemonk** [typicode/hotel#18]
the log says it all
```
$ npm install -g hotel
 
> hotel@0.2.10 prepublish /home/git_user/src/hotel
> npm test

/
> hotel@0.2.10 test /home/git_user/src/hotel
> npm run build && npm run standard && mocha

-
> hotel@0.2.10 build /home/git_user/src/hotel
> babel src --out-dir lib --copy-files

module.js:338
    throw err;
          ^
Error: Cannot find module 'babel-core/lib/babel/transformation/modules'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/git_user/src/hotel/node_modules/.bin/babel:3:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! hotel@0.2.10 build: `babel src --out-dir lib --copy-files`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hotel@0.2.10 build script 'babel src --out-dir lib --copy-files'.
npm ERR! This is most likely a problem with the hotel package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src --out-dir lib --copy-files
npm ERR! You can get their info via:
npm ERR!     npm owner ls hotel
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/git_user/src/hotel/npm-debug.log
npm ERR! Test failed.  See above for more details.

npm ERR! addLocalDirectory Could not pack /home/git_user/src/hotel to /home/git_user/.npm/hotel/0.2.10/package.tgz
npm ERR! addLocal Could not install /home/git_user/src/hotel
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "hotel"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! hotel@0.2.10 prepublish: `npm test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hotel@0.2.10 prepublish script 'npm test'.
npm ERR! This is most likely a problem with the hotel package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm test
npm ERR! You can get their info via:
npm ERR!     npm owner ls hotel
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/git_user/src/npm-debug.log
```

**Comment by typicode** [comment]
Not sure to understand everything. Actually, I don't understand why the `prepublish` and `test` scripts are started?

When I do `npm install -g hotel`, I'm getting this:

```
$ npm install -g hotel

> ws@0.5.0 install /home/typicode/.nvm/versions/node/v0.12.5/lib/node_modules/hotel/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/typicode/.nvm/versions/node/v0.12.5/lib/node_modules/hotel/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/home/typicode/.nvm/versions/node/v0.12.5/lib/node_modules/hotel/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
 
> ws@0.4.31 install /home/typicode/.nvm/versions/node/v0.12.5/lib/node_modules/hotel/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/typicode/.nvm/versions/node/v0.12.5/lib/node_modules/hotel/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/home/typicode/.nvm/versions/node/v0.12.5/lib/node_modules/hotel/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
/home/typicode/.nvm/versions/node/v0.12.5/bin/hotel -> /home/typicode/.nvm/versions/node/v0.12.5/lib/node_modules/hotel/bin/index.js

> hotel@0.2.10 install /home/typicode/.nvm/versions/node/v0.12.5/lib/node_modules/hotel
> node bin/install


  Create  ~/.config/autostart/hotel.desktop
  Created startup script 

  Create  ~/.hotel/daemon.log
  Spawn   ~/.nvm/versions/node/v0.12.5/bin/node ~/.nvm/versions/node/v0.12.5/lib/node_modules/hotel/lib/daemon
  Started http://localhost:2000

  To uninstall: npm rm -g hotel

hotel@0.2.10 /home/typicode/.nvm/versions/node/v0.12.5/lib/node_modules/hotel
├── get-port@1.0.0
├── unquote@1.1.0
├── xtend@4.0.0
├── untildify@2.1.0 (os-homedir@1.0.0)
├── tildify@1.1.0 (os-homedir@1.0.0)
├── downgrade-root@1.1.0 (is-root@1.0.0, default-uid@1.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── sudo-block@1.2.0 (is-root@1.0.0, is-docker@1.0.0, chalk@1.0.0)
├── watch@0.16.0 (minimist@1.1.1, exec-sh@0.2.0)
├── got@2.9.2 (lowercase-keys@1.0.0, timed-out@2.0.0, is-stream@1.0.1, prepend-http@1.0.1, object-assign@2.1.1, nested-error-stacks@1.0.0, statuses@1.2.1, infinity-agent@2.0.3, read-all-stream@2.2.0, duplexify@3.4.2)
├── yargs@3.12.0 (decamelize@1.0.0, camelcase@1.1.0, window-size@0.1.1, cliui@2.1.0)
├── express@4.13.0 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.0, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, range-parser@1.0.2, path-to-regexp@0.1.6, etag@1.7.0, content-type@1.0.1, vary@1.0.0, parseurl@1.3.0, content-disposition@0.5.0, serve-static@1.10.0, depd@1.0.1, qs@2.4.2, finalhandler@0.4.0, on-finished@2.3.0, debug@2.2.0, proxy-addr@1.0.8, send@0.13.0, type-is@1.6.3, accepts@1.2.9)
├── update-notifier@0.5.0 (is-npm@1.0.0, string-length@1.0.0, configstore@1.1.0, chalk@1.0.0, repeating@1.1.3, semver-diff@2.0.0, latest-version@1.0.1)
├── respawn-group@1.0.1 (after-all@1.1.0, respawn@1.1.0)
└── socket.io@1.3.5 (debug@2.1.0, has-binary-data@0.1.3, socket.io-adapter@0.3.1, socket.io-parser@2.2.4, engine.io@1.5.1, socket.io-client@1.3.5)
```

**Comment by veggiemonk** [comment]
does it has something to do with #8?
Maybe you had babel installed globally before doing: <code>npm install -g hotel</code>
Which is why it might be a good idea to warn about dependencies... or make them installed with <code>npm install</code>. Hence the suggestion of @rstacruz #8 
What do you think?

**Comment by typicode** [comment]
I don't think so or at least not aware of. I just did a test on a fresh linux install.

Based on this https://docs.npmjs.com/misc/scripts `prepublish` script should only run on `npm publish` or `npm install`.

In any case, will release something soon.

**Comment by typicode** [comment]
Just released `v0.3`, you can run `npm update -g hotel` to get the latest version :)

**Comment by veggiemonk** [comment]
Awesome!! thanks!

**Comment by typicode** [comment]
Glad it works :)
Thanks for closing.
