### ISSUE TITLE
Wrong path for `please-upgrade-node` module

### ISSUE THREAD

**Issue by the0neyouseek** [typicode/hotel#210]
`please-upgrade-node` can't resolve `../package.json` (because it doesn't exist) and those leading to hotel crashing on launch, for example :

```js
hotel start
module.js:487
    throw err;
    ^

Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports (/Users/anon/.nvm/versions/node/v8.2.1/lib/node_modules/hotel/node_modules/please-upgrade-node/index.js:3:13)
    at Object.<anonymous> (/Users/anon/.nvm/versions/node/v8.2.1/lib/node_modules/hotel/lib/cli/bin.js:4:31)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```
**Solution** : The correct path seems to be `../../package.json` so you need to change `'..'` to `'../..'` on line 4 of `lib/cli/bin.js`

**Comment by RickyShiJs** [comment]
Also found it, it happens in 0.7.5, you can use npm install -g hotel@0.7.4 to use the legacy version instead.
https://github.com/typicode/hotel/issues/211

**Comment by typicode** [comment]
My bad, thanks for the heads up

**Comment by typicode** [comment]
Should be good with 0.7.6 ;)
