### ISSUE TITLE
new version 0.7.5 will throw out a exception in macOs when start 

### ISSUE THREAD

**Issue by RickyShiJs** [typicode/hotel#211]
If i install 0.7.4, all things work. But 0.7.5 will throw out below exception

Error: Cannot find module '../package.json'

**Comment by typicode** [comment]
Hi,

0.7.6 should fix it ;)

**Comment by jacoswarts** [comment]
Hi there,

I have 0.7.6 but get the following on using any `hotel` cli commands:

```
module.js:515
    throw err;
    ^

Error: Cannot find module '../../package.json'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/bin/hotel:4:11)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
```

Have latest node (8.8.0) installed with nvm.

Any ideas?
