### ISSUE TITLE
A fresh installation throws ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by THPubs** [typicode/hotel#300]
I just installed hotel in a new machine and from any browser I can't access the tool. It says `This site can’t be reached. ERR_CONNECTION_REFUSED`. In the `daemon.log` I can see the following error:

    /Users/pubudu/.config/yarn/global/node_modules/eventemitter3/index.js:60
        throw new TypeError('The listener must be a function');
        ^

    TypeError: The listener must be a function
        at addListener (/Users/pubudu/.config/yarn/global/node_modules/eventemitter3/index.js:60:11)
        at ProxyServer.on (/Users/pubudu/.config/yarn/global/node_modules/eventemitter3/index.js:228:10)
        at new Group (/Users/pubudu/.config/yarn/global/node_modules/hotel/lib/daemon/group.js:33:17)
        at module.exports (/Users/pubudu/.config/yarn/global/node_modules/hotel/lib/daemon/group.js:23:24)
        at Object.<anonymous> (/Users/pubudu/.config/yarn/global/node_modules/hotel/lib/daemon/index.js:13:15)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
    /Users/pubudu/.config/yarn/global/node_modules/eventemitter3/index.js:60
        throw new TypeError('The listener must be a function');
        ^

Any idea what's happening?

**Comment by djanowski** [comment]
This seems to be a regression with http-proxy 1.17.

**Comment by jameswlane** [comment]
Fresh install also:

```
TypeError: The listener must be a function
    at addListener (/Users/jameswlane/.nvm/versions/node/v8.10.0/lib/node_modules/hotel/node_modules/eventemitter3/index.js:60:11)
    at ProxyServer.on (/Users/jameswlane/.nvm/versions/node/v8.10.0/lib/node_modules/hotel/node_modules/eventemitter3/index.js:228:10)
    at new Group (/Users/jameswlane/.nvm/versions/node/v8.10.0/lib/node_modules/hotel/lib/daemon/group.js:33:17)
    at module.exports (/Users/jameswlane/.nvm/versions/node/v8.10.0/lib/node_modules/hotel/lib/daemon/group.js:23:24)
    at Object.<anonymous> (/Users/jameswlane/.nvm/versions/node/v8.10.0/lib/node_modules/hotel/lib/daemon/index.js:13:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
/Users/jameswlane/.nvm/versions/node/v8.10.0/lib/node_modules/hotel/node_modules/eventemitter3/index.js:60
    throw new TypeError('The listener must be a function');
    ^

```

**Comment by typicode** [comment]
Thanks for the heads up, it should be better with Hotel `v0.8.6` :)

**Comment by osman-mohamad** [comment]
I have the same error and I use v0.8.7 on ubuntu

**Comment by j-f1** [comment]
Looks like you already have something running on port 2001.

**Comment by osman-mohamad** [comment]
@j-f1 where the 2001 port is used by hotel ?

**Comment by j-f1** [comment]
The proxy server uses port `conf.port + 1`. If you change the `port` in `~/.hotel/conf.json`, you should be able to get rid of the error, although you’ll need to reconfigure your proxy settings.

**Comment by osman-mohamad** [comment]
@j-f1 the error is gone in the daemon.log file . but the problem is still here.
and I opened a new issue about it .
