### ISSUE TITLE
Hotel crash on server stop.

### ISSUE THREAD

**Issue by melMass** [typicode/hotel#328]
When I untick a running server from hotel's ui it crashes hotel right after:

```
21:44:40 - Proxy - http://mac-backend.localhost → http://localhost:61544
21:44:41 - Resolve mac-backend
21:44:41 - Proxy - http://mac-backend.localhost → http://localhost:61544
21:44:41 - Resolve mac-backend
21:44:41 - Proxy - http://mac-backend.localhost → http://localhost:61544
21:44:45 - Resolve mac-backend
21:44:45 - Proxy - http://mac-backend.localhost → http://localhost:61544
21:44:45 - Resolve mac-backend
21:44:45 - Proxy - http://mac-backend.localhost → http://localhost:61544
21:45:26 - Resolve mac-backend
21:45:26 - Proxy - http://mac-backend.localhost → http://localhost:61544
21:45:27 - Resolve mac-backend
21:45:27 - Proxy - http://mac-backend.localhost → http://localhost:61544
21:45:29 - Resolve mac-backend
21:45:29 - Proxy - http://mac-backend.localhost → http://localhost:61544
21:45:29 - Resolve mac-backend
21:45:29 - Proxy - http://mac-backend.localhost → http://localhost:61544
21:45:35 - Resolve mac-backend
(node:53998) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 stop listeners added. Use emitter.setMaxListeners() to increase limit
Exiting
Stop daemon
Remove pid file
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by melMass** [comment]
My workaround for now is to add the following to `hotel.plist`. This will relaunch the command on fail/exit
```plist
<key>KeepAlive</key>
```
