### ISSUE TITLE
Socket hang up error with multiple subdomains Ubuntu 20.04

### ISSUE THREAD

**Issue by shivam-kantival-mt** [typicode/hotel#373]
I have a proxy configured as with filename _***.example**_
`{
  "target": "http://127.0.0.1:8011"
}`

The same successfully serves **_a.example.local_**, but not _**b.a.example.local**_. The later request timesout and following error is logged in daemon logs-
`Error: socket hang up
    at connResetException (internal/errors.js:610:14)
    at Socket.socketCloseListener (_http_client.js:400:25)
    at Socket.emit (events.js:327:22)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}`

I tried to see the diff in request object in _**daemon/group.js**_, but couldn't find anything significant. The only difference is in the host and x-forwarded-host header.

**Comment by shivam-kantival-mt** [comment]
It was a code fault at the server end. It was getting stuck infinitely.
